<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
		<RootNamespace>DamageMaker</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>False</UseWindowsForms>
		<SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>Resources\rail_icon_180532.ico</ApplicationIcon>
		<NeutralLanguage>zh-Hans</NeutralLanguage>
		<DefineConstants>WINDOWS</DefineConstants>
		<Configurations>Debug;Release;BEIJING</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>7</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>7</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='BEIJING|AnyCPU'">
	  <WarningLevel>7</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="file\**" />
		<EmbeddedResource Remove="file\**" />
		<None Remove="file\**" />
		<Page Remove="file\**" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="R-C.jpg" />
		<None Remove="Resources\Logo.png" />
		<None Remove="Resources\ShanHeZhongZhiLogo.png" />
		<None Remove="Resources\p_new0521_l_new05210.jpg" />
		<None Remove="Resources\R-C.jpg" />
		<None Remove="Resources\tile.jpg" />
		<None Remove="R-C.jpg" />
		<None Remove="Resources\Logo.png" />
		<None Remove="Resources\p_new0521_l_new05210.jpg" />
		<None Remove="Resources\tile.jpg" />
	</ItemGroup>
	<ItemGroup>
	  <COMReference Include="IWshRuntimeLibrary">
	    <WrapperTool>tlbimp</WrapperTool>
	    <VersionMinor>0</VersionMinor>
	    <VersionMajor>1</VersionMajor>
	    <Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
	    <Lcid>0</Lcid>
	    <Isolated>false</Isolated>
	    <EmbedInteropTypes>true</EmbedInteropTypes>
	  </COMReference>
	</ItemGroup>

	<ItemGroup>
		<Content Include="Resources\rail_icon_180532.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="DocX" Version="4.0.25105.5786" />
		<PackageReference Include="FlaUI.UIA3" Version="5.0.0" />
		<PackageReference Include="HandyControl" Version="3.5.1" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.7" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
		<PackageReference Include="SQLitePCLRaw.provider.winsqlite3" Version="2.1.11" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\p_new0521_l_new05210.jpg" />
		<Resource Include="Resources\Logo.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\ShanHeZhongZhiLogo.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\tile.jpg" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
		  <DesignTime>True</DesignTime>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Resources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<None Update="DB\Dm.db">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
		
		<None Update="Resources\excel模板.xlsx">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		
		<None Update="Resources\excel模板SH.xlsx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\excel模版.xlsx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\word报告模板2.docx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\word报告模板1.docx">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\钢轨探伤检测报告模板.docx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\上海报告.docx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Resources\上海表格.xlsx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Resources\Temp\" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties />
		</VisualStudio>
	</ProjectExtensions>
</Project>
