//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DamageMaker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ScreenshotOffset {
            get {
                return ((int)(this["ScreenshotOffset"]));
            }
            set {
                this["ScreenshotOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ScreenshotInterval {
            get {
                return ((int)(this["ScreenshotInterval"]));
            }
            set {
                this["ScreenshotInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSelectedFolder {
            get {
                return ((string)(this["LastSelectedFolder"]));
            }
            set {
                this["LastSelectedFolder"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Publish\\StartScript\\StartScript.exe")]
        public string PythonScriptLocation {
            get {
                return ((string)(this["PythonScriptLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE")]
        public string OfficeLocation {
            get {
                return ((string)(this["OfficeLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Snipaste-2.9.1-Beta-x64\\Snipaste.exe")]
        public string Snipaste {
            get {
                return ((string)(this["Snipaste"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\ImgFile\\\\in")]
        public string InPath {
            get {
                return ((string)(this["InPath"]));
            }
            set {
                this["InPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\DocxsPath")]
        public string DocxPath {
            get {
                return ((string)(this["DocxPath"]));
            }
            set {
                this["DocxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\yolov9-main\\demo.py")]
        public string YoloLocation {
            get {
                return ((string)(this["YoloLocation"]));
            }
            set {
                this["YoloLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int MouseMovePixel {
            get {
                return ((int)(this["MouseMovePixel"]));
            }
            set {
                this["MouseMovePixel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\TrackData")]
        public string TrackData {
            get {
                return ((string)(this["TrackData"]));
            }
            set {
                this["TrackData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\ExcelsPath")]
        public string ExcelsPath {
            get {
                return ((string)(this["ExcelsPath"]));
            }
            set {
                this["ExcelsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsDistictRepeat {
            get {
                return ((bool)(this["IsDistictRepeat"]));
            }
            set {
                this["IsDistictRepeat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\DB\\\\Dm.db")]
        public string SqlPath {
            get {
                return ((string)(this["SqlPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsConcealFishScale {
            get {
                return ((bool)(this["IsConcealFishScale"]));
            }
            set {
                this["IsConcealFishScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\\\ImgFile\\\\out")]
        public string OutPath {
            get {
                return ((string)(this["OutPath"]));
            }
            set {
                this["OutPath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>D:\work\E\铁路超声波探伤判伤\探伤\回放软件\JGT-6M免安装版\软件\JGT-6M回放软件免安装版\JGT-6M信息管理.exe</string>
  <string>D:\work\E\铁路超声波探伤判伤\探伤\回放软件\RailTest免安装版\软件\RailTest\RailTest.exe</string>
  <string>D:\回放软件\CT19_V372\CTKJ-436.exe</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AppLocation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AppLocation"]));
            }
        }
    }
}
